-- Activate plugins
local activate = require "activate"

return {
  -- core plugins
  require "plugins.core.treesitter"(activate.treesitter),
  require "plugins.core.lspconfig"(activate.lspconfig),
  require "plugins.core.mason_lspconfig"(activate.mason_lspconfig),
  require "plugins.core.lint"(activate.lint),
  require "plugins.core.mason_lint"(activate.mason_lint),
  require "plugins.core.conform"(activate.conform),
  require "plugins.core.mason_conform"(activate.mason_conform),
  require "plugins.core.cmp"(activate.cmp),
  require "plugins.core.telescope"(activate.telescope),
  require "plugins.core.gitsigns"(activate.gitsigns),
  require "plugins.core.toggleterm"(activate.toggleterm),
  require "plugins.core.lspsaga"(activate.lspsaga),

  -- ui plugins
  require "plugins.ui.nvim_tree"(activate.nvim_tree),
  require "plugins.ui.indent_blankline"(activate.indent_blankline),
  require "plugins.ui.noice"(activate.noice),
  require "plugins.ui.dressing"(activate.dressing),
  require "plugins.ui.flash"(activate.flash),
  require "plugins.ui.neoscroll"(activate.neoscroll),
  require "plugins.ui.highlighturl"(activate.highlighturl),
  require "plugins.ui.fold"(activate.fold),

  -- misc plugins
  require "plugins.misc.editorconfig"(activate.editorconfig),
  require "plugins.misc.case_change"(activate.case_change),
  require "plugins.misc.boole"(activate.boole),
  require "plugins.misc.quit"(activate.quit),
  require "plugins.misc.move"(activate.move),
  require "plugins.misc.duplicate"(activate.duplicate),
  require "plugins.misc.yanky"(activate.yanky),
  require "plugins.misc.visual_multi"(activate.visual_multi),
  require "plugins.misc.bookmarks"(activate.bookmarks),
  require "plugins.misc.silicon"(activate.silicon),
  require "plugins.misc.spectre"(activate.spectre),
  require "plugins.misc.rename"(activate.rename),
  require "plugins.misc.comment"(activate.comment),
  require "plugins.misc.surround"(activate.surround),
  require "plugins.misc.todo_comments"(activate.todo_comments),
  require "plugins.misc.vim_tmux"(activate.vim_tmux),
  require "plugins.misc.persistence"(activate.persistence),
  require "plugins.misc.illuminate"(activate.illuminate),
  require "plugins.misc.session"(activate.session),
  require "plugins.misc.undotree"(activate.undotree),
  require "plugins.misc.trouble"(activate.trouble),
  require "plugins.misc.vim_maximizer"(activate.maximizer),
  require "plugins.misc.substitute"(activate.substitute),
  require "plugins.misc.goto_preview"(activate.goto_preview),
  require "plugins.misc.database"(activate.database),
}
